
brew 'adr-tools'
cask 'alfred'
brew 'ansible'
brew 'argocd'
brew 'asdf'
brew 'bash-completion'
brew 'bat'
cask 'bitwarden'
cask 'chromium'
brew 'commitizen'
brew 'coreutils'
# cask 'crossover'
brew 'curl'
brew 'dagger'
brew 'exiftool'
cask 'firefox'
brew 'ffmpeg'
brew 'fprobe'
brew 'fzf'
cask 'google-drive'
brew 'graphviz'
brew 'htop'
brew 'hugo'
cask 'iterm2'
brew 'jenv'
brew 'jq'
brew 'mas'
brew 'mkdocs'
brew 'neovim'
cask 'obsidian'
# brew 'pass'
cask 'rectangle'
cask 'slack'
cask 'snagit'
brew 'starship'
cask 'steam'
brew 'stow'
brew 'telnet'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'vim'
cask 'visual-studio-code'
brew 'watch'
brew 'wget'
cask 'whatsapp'
brew 'yq'
brew 'yt-dlp'
cask 'yubico-yubikey-manager'
cask 'xbar'
cask 'zoom'
## fonts
# cask 'homebrew/cask-fonts'
cask 'font-hack-nerd-font'

# api
cask 'postman'
cask 'postman-cli'

# cloud
## AWS
brew 'awscli'
# brew 'turbot/tap/steampipe'
## GCP 
cask 'google-cloud-sdk'

# git
brew 'git'
# cask 'gitkraken'
brew 'gh'
cask 'git-credential-manager'
brew 'lazygit'

# go
brew 'golang'
brew 'go-task'

#IaC
## opentofu
brew 'opentofu'
## terraform
# brew 'terraform' # use asdf instead
brew 'terraform-docs'
# brew 'tfenv' - removed so the CloudPosse tfenv can be installed
## terragrunt
brew 'terragrunt'
## terramate
brew 'terramate'
## visualizer
tap 'inkdrop-org/inkdrop-visualizer'
brew 'inkdrop-visualizer'

# rdbms
cask 'pgadmin4'
cask 'datasette'

# virtual
## k8s
brew 'helm'
brew 'k9s'
brew 'kubectl'
brew 'kubectx'
# brew 'kustomize'
brew 'krew'
# cask 'rancher'
brew 'clusterctl'
## vagrant
cask 'vagrant'

## talos

brew 'talosctl'

## docker

## podman

cask 'podman-desktop'
brew 'podman'
brew 'podman-compose'
brew 'podman-tui'

# python
brew 'pyenv'
brew 'python3'
brew 'ipython'
brew 'pipx'
brew 'poetry'

# secrets
## vault
brew 'vault'
## 1password
cask '1password'
cask '1password-cli'

# zsh
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'zsh-fast-syntax-highlighting'

# mas installs
mas 'Todoist', id: 585829637
# mas 'Magnet', id: 441258766
mas '1Password for Safari', id: 1569813296
# mas 'Notability', id: 360593530
mas 'iStat Menus', id: 1319778037
# mas 'Xcode', id: 497799835
